Support pick directory and save file without dialog
kineapps/flutter_file_dialog pull request #36
Opened 2022-10-04 09:55 UTC by Doflatango

This PR added three methods for saving files and will not displays any pops after picking a directory.
This is very useful when you have multiple files to save in the same directory.

1. `pickDirectory()` pick a directory where files will be saved to.
2. `saveFileToDirectory()` use a directory that pick by `pickDirectory()` for save multiple files without pops.
3. `isSupportPickDirectory()` check whether the current platform supports `pickDirectory()` or not if you are targeting an older version of Android/iOS.

2023-01-13 14:41 UTC, RJustoX commented
⬆️ ⬆️ ⬆️

2023-01-13 20:19 UTC, kinex commented
Thanks for the PR and sorry I have forgot to review this earlier. Looks interesting, I will review this soon.

2023-01-16 15:15 UTC, kinex requested changes
Looks really great! Only thing that I didn't like is the name "isSupportPickDirectory". I suggest renaming it either as "canPickDirectory" or "isPickDirectorySupported".

2023-01-17 03:51 UTC, Doflatango commented
> Looks really great! Only thing that I didn't like is the name "isSupportPickDirectory". I suggest renaming it either as "canPickDirectory" or "isPickDirectorySupported".

@kinex Done!

2023-01-17 14:57 UTC, merged